spring:
  application:
    name: login_rf_test
  datasource:
    url: ${ODBURL_TEST}
    driver-class-name: org.h2.Driver
    username: ${ODBUSERNAME_TEST}
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAILFORSEND}
    password: ${PASSMAILAPP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    addresses: ${AMQPADDRESS}

server:
  port: 8081