spring:
  application:
    name: login_rf_test
  config:
    activate:
      on-profile: test
  datasource:
    jdbc-url: ${ODBURL}
    username: ${ODBUSERNAME}
    password: ${ODBPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAILFORSEND}
    password: ${PASSMAILAPP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    addresses: ${AMQPADDRESS}

server:
  port: 8081