spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAILFORSEND}
    password: ${PASSMAILAPP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true