name: Docker-Build-Store

on:
  workflow_run:
    workflows:
      - Togo-Backend-lrf
    types:
      - completed

jobs:
  build-and-store:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t ${{ secrets.IMAGE_NAME }}:${{secrets.IMAGE_VERSION_ONE}} .

      - name: Login into Azure Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push docker image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_VERSION_ONE }}

