name: Togo-Backend-lrf

env:
  SPRING_PROFILES_ACTIVE: test
  ODBURL_TEST: ${{secrets.ODBURL_TEST}}
  ODBUSERNAME_TEST: ${{secrets.ODBUSERNAME_TEST}}
  MAILFORSEND: ${{secrets.MAILFORSEND}}
  PASSMAILAPP: ${{secrets.PASSMAILAPP}}
  AMQPADDRESS: ${{secrets.AMQPADDRESS}}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with mvn wrapper
        run: ./mvnw clean package -DskipTests -X

      - name: Successfully run
        run: echo "Run Successfully"